### ISSUE TITLE
Erro ao realizar transformação extrai_grupos.ktr

### ISSUE THREAD

**Issue by rdccosmo** [LEDS/sipac#30]
2016/05/17 13:17:45 - Tabela Grupos - saida.0 - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : Unexpected batch update error committing the database connection.
2016/05/17 13:17:45 - Tabela Grupos - saida.0 - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : org.pentaho.di.core.exception.KettleDatabaseBatchException: 
2016/05/17 13:17:45 - Tabela Grupos - saida.0 - Error updating batch
2016/05/17 13:17:45 - Tabela Grupos - saida.0 - Batch entry 0 INSERT INTO "public".agricultura_grupo (nome_grupo, grupo_id, id) VALUES ( 'Agricultura',  NULL,  5) was aborted.  Call getNextException to see the cause.
2016/05/17 13:17:45 - Tabela Grupos - saida.0 - 
2016/05/17 13:17:45 - Tabela Grupos - saida.0 -     at org.pentaho.di.core.database.Database.createKettleDatabaseBatchException(Database.java:1379)
2016/05/17 13:17:45 - Tabela Grupos - saida.0 -     at org.pentaho.di.core.database.Database.emptyAndCommit(Database.java:1368)
2016/05/17 13:17:45 - Tabela Grupos - saida.0 -     at org.pentaho.di.trans.steps.tableoutput.TableOutput.dispose(TableOutput.java:575)
2016/05/17 13:17:45 - Tabela Grupos - saida.0 -     at org.pentaho.di.trans.step.RunThread.run(RunThread.java:96)
2016/05/17 13:17:45 - Tabela Grupos - saida.0 -     at java.lang.Thread.run(Thread.java:745)
2016/05/17 13:17:45 - Tabela Grupos - saida.0 - Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "public".agricultura_grupo (nome_grupo, grupo_id, id) VALUES ( 'Agricultura',  NULL,  5) was aborted.  Call getNextException to see the cause.
2016/05/17 13:17:45 - Tabela Grupos - saida.0 -     at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
2016/05/17 13:17:45 - Tabela Grupos - saida.0 -     at org.postgresql.core.v3.QueryExecutorImpl$1.handleError(QueryExecutorImpl.java:461)
2016/05/17 13:17:45 - Tabela Grupos - saida.0 -     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
2016/05/17 13:17:45 - Tabela Grupos - saida.0 -     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
2016/05/17 13:17:45 - Tabela Grupos - saida.0 -     at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
2016/05/17 13:17:45 - Tabela Grupos - saida.0 -     at org.pentaho.di.core.database.Database.emptyAndCommit(Database.java:1355)

**Comment by Sakamotto** [comment]
Olha no banco. Na tabela agricultura_grupo. Esse erro aparece quando os dados já foram inseridos e você está tentando inserir no novamente.

**Comment by rdccosmo** [comment]
Ok, @Sakamotto era isso mesmo.
Fechando issue.
