### ISSUE TITLE
Erro ao realizar transformação extrai_producao.ktr

### ISSUE THREAD

**Issue by rdccosmo** [LEDS/sipac#31]
Ao que parece o campo válido não pode ser nulo, mas ele não consta na cláusula de inserção:

> 2016/05/18 14:29:15 - Tabela Produção.0 - Error batch inserting rows into table [agricultura_producao].
> 2016/05/18 14:29:15 - Tabela Produção.0 - Errors encountered (first 10):
> 2016/05/18 14:29:15 - Tabela Produção.0 - ERROR: null value in column "valido" violates not-null constraint
> 2016/05/18 14:29:15 - Tabela Produção.0 -   Detail: Failing row contains (2, 2014, 4, 20, 50, 20, null, S, 33, 69, null).
> 2016/05/18 14:29:15 - Tabela Produção.0 - 
> 2016/05/18 14:29:15 - Tabela Produção.0 - 
> 2016/05/18 14:29:15 - Tabela Produção.0 - Error updating batch
> 2016/05/18 14:29:15 - Tabela Produção.0 - Batch entry 0 INSERT INTO "public".agricultura_producao (ano, mes, area_plantada, producao, area_colhida, area_em_formacao, irrigado, municipio_id, produto_id) VALUES ( 2014,  4,  20,  50,  20,  NULL,  'S',  33,  69) was aborted.  Call getNextException to see the cause.

**Comment by LEDS** [comment]
Isso aqui já foi resolvido?

**Comment by rdccosmo** [comment]
Ainda não foi resolvido.

**Comment by LEDS** [comment]
aberto novamente :)

**Comment by paulossjunior** [comment]
Prezados o Issue foi resolvido?

**Comment by rdccosmo** [comment]
Volto a realizar novos testes amanhã, mas ainda não foi resolvido.

**Comment by rdccosmo** [comment]
Na documentação do Django sobre migrations:

> AlterField
> 
> class AlterField(model_name, name, field, preserve_default=True)[source]
> Alters a field’s definition, including changes to its type, null, unique, db_column and other field attributes.
> 
> The preserve_default argument indicates whether the field’s default value is permanent and should be baked into the project state (True), or if it is temporary and just for this migration (False) - usually because the migration is altering a nullable field to a non-nullable one and needs a default value to put into existing rows. **It does not affect the behavior of setting defaults in the database directly - Django never sets database defaults and always applies them in the Django ORM code**.
> 
> Note that not all changes are possible on all databases - for example, you cannot change a text-type field like models.TextField() into a number-type field like models.IntegerField() on most databases.

Portanto https://github.com/LEDS/sipac-backend/tree/master/sipac/agricultura/migrations/0003_auto_20160223_1431.py#L37 não tem efeito no banco de dados. Só funcionaria se fosse o ORM do django a persistir os dados no banco. Depois que setei o valor default da coluna valido como TRUE a transformação passou a funcionar.

Vou fechar este issue e criar outro pra valor default da coluna  agricultura_producao.valido.
