### ISSUE TITLE
Conexão de banco de dados local

### ISSUE THREAD

**Issue by rdccosmo** [LEDS/sipac#42]
Sugiro a mudança do host de banco de dados para `db`:
- nos relatórios: Sempre que os relatórios devem ser editados, deve-se configurar todas as conexões para refletir a arquitetura local, que pode ter a instância do banco de dados em outro servidor
- na configuração do django
- nos arquivos de transformação

Substituindo o host de `localhost` para `db` torna possível:
- o funcionamento as-is via docker-compose, já que a entrada do banco já usa esse alias
- que o host `db`seja configurado para apontar para `localhost` ou outro endereço (via /etc/hosts), possibilitando maior flexibilidade

**Comment by rdccosmo** [comment]
Algum posicionamento para esse issue?

É uma coisa que facilitaria muito, pois toda vez que os relatórios são atualizados é preciso ir em cada um e editar as conexões com o banco de dados.

Caso eu tenha vários ambientes para testes e homologação, como é o meu caso, preciso fazer isso várias vezes.

**Comment by Sakamotto** [comment]
Okay, nós podemos mudar aqui. A senha ainda continua a mesma, correto? Só preciso mudar o nome da conexão?

**Comment by rdccosmo** [comment]
a senha é a mesma. Na verdade é o nome do host: substituir **localhost** por **db**

**Comment by Sakamotto** [comment]
Bom dia, Rodrigo. Viu que mudamos a conexão para db? Deu tudo certo aí?

**Comment by rdccosmo** [comment]
tudo :ok_hand: @Sakamotto 
muito bom não ter que editar todas aquelas conexões

**Comment by rdccosmo** [comment]
@Sakamotto testei agora a transformacao extrai_producao.ktr e a conexao estava com localhost ainda. lembrando que novas cargas de dados sao feitas via transformacao

**Comment by paulossjunior** [comment]
pode fechar?

**Comment by rdccosmo** [comment]
vou testar as alterações feitas em 47e0a67
