### ISSUE TITLE
Expression references invalid field in property Field Name

### ISSUE THREAD

**Issue by rdccosmo** [LEDS/sipac#43]
O relatório relatorio_participacao_percentual_area_colhida.prpt apresenta esta mensagem ao pré-visualizar:

> WARNING: Expression 'soma_producao_total_regiao' references invalid field 'producao_total' in property 'Field Name'.

**Comment by Sakamotto** [comment]
Boa tarde, Rodrigo. Você está com a versão mais atual do relatório? Eu executei ele aqui e está tudo normal.

**Comment by rdccosmo** [comment]
vou testar amanha

**Comment by rdccosmo** [comment]
No report designer esse relatório exibe a mensagem de aviso abaixo, mas exibe os dados. Vou fechar a issue.

> Warning: Data-Set does not contain a column with name 'producao_total'
