### ISSUE TITLE
ERROR: function valida_valor(integer, integer, integer) does not exist

### ISSUE THREAD

**Issue by rdccosmo** [LEDS/sipac#44]
O relatório [Modelo Drive](/LEDS/sipac-backend/blob/master/dados_teste/sqls/Relatorios/Relatorio%20Modelo%20Drive.prpt) dá o seguinte erro no report designer:

> org.pentaho.reporting.engine.classic.core.ReportDataFactoryException: Failed at query: SELECT
> grupo.nome_grupo,
> INITCAP(produto.nome),
> CASE WHEN ${regiao}='Estado' THEN estado.nome
>   WHEN ${regiao}='Mesorregião' THEN mesorregiao.nome
>   WHEN ${regiao}='Microrregião' THEN microrregiao.nome
>   WHEN ${regiao}='Município' THEN municipio.nome
> END AS REGIAO_NOME,
> 
> SUM(valida_valor(${escolha_do_ano_1}, producao.ano, producao.area_colhida)) AS AREA_COLHIDA_ANTERIOR_TOTAL,
> 
> SUM(valida_valor(${escolha_do_ano_1}, producao.ano, producao.producao)) AS PRODUCAO_ANTERIOR_TOTAL,
> 
> rendimento_medio(
>   SUM(CASE WHEN ${escolha_do_ano_1} = producao.ano THEN producao.area_colhida ELSE 0 END),
>   SUM(CASE WHEN ${escolha_do_ano_1} = producao.ano THEN producao.producao ELSE 0 END)
> ) AS RENDIMENTO_MEDIO_ANTERIOR_TOTAL,
> 
> SUM(valida_valor(${escolha_do_ano_2}, producao.ano, producao.area_colhida)) AS AREA_COLHIDA_ATUAL_TOTAL,
> 
> SUM(valida_valor(${escolha_do_ano_2}, producao.ano, producao.producao)) AS PRODUCAO_ATUAL_TOTAL,
> 
> rendimento_medio(
>   SUM(CASE WHEN ${escolha_do_ano_2} = producao.ano THEN producao.area_colhida ELSE 0 END),
>   SUM(CASE WHEN ${escolha_do_ano_2} = producao.ano THEN producao.producao ELSE 0 END)
> ) AS RENDIMENTO_MEDIO_ATUAL_TOTAL,
> 
> variacao_p(SUM(valida_valor(${escolha_do_ano_1}, producao.ano, producao.area_colhida)),
> SUM(valida_valor(${escolha_do_ano_2}, producao.ano, producao.area_colhida))) AS VARIACAO_AREA_COLHIDA,
> 
> variacao_p(SUM(valida_valor(${escolha_do_ano_1}, producao.ano, producao.producao)),
> SUM(valida_valor(${escolha_do_ano_2}, producao.ano, producao.producao))) AS VARIACAO_PRODUCAO,
> 
> variacao_p(
> 
>   rendimento_medio(
>       SUM(CASE WHEN ${escolha_do_ano_1} = producao.ano THEN producao.area_colhida ELSE 0 END),
>       SUM(CASE WHEN ${escolha_do_ano_1} = producao.ano THEN producao.producao ELSE 0 END)
>   ),
> 
>   rendimento_medio(
>       SUM(CASE WHEN ${escolha_do_ano_2} = producao.ano THEN producao.area_colhida ELSE 0 END),
>       SUM(CASE WHEN ${escolha_do_ano_2} = producao.ano THEN producao.producao ELSE 0 END)
>   )
> 
> ) AS VARIACAO_RENDIMENTO
> 
> -- Fim Variação Total
> 
> FROM
> agricultura_produto AS produto
> INNER JOIN agricultura_producao AS producao ON produto.id = producao.produto_id
> INNER JOIN agricultura_grupo AS grupo ON produto.grupo_id = grupo.id
> INNER JOIN core_municipio as municipio on municipio.id = producao.municipio_id
> INNER JOIN core_estado AS estado ON municipio.estado_id = estado.id
> INNER JOIN core_microregiao AS microrregiao ON microrregiao.id = municipio.microregiao_id
> INNER JOIN core_mesoregiao AS mesorregiao ON mesorregiao.id = microrregiao.mesoregiao_id
> 
> WHERE
> (CASE WHEN ${regiao}='Estado' THEN estado.nome
>   WHEN ${regiao}='Mesorregião' THEN mesorregiao.nome
>   WHEN ${regiao}='Microrregião' THEN microrregiao.nome
>   WHEN ${regiao}='Município' THEN municipio.nome
> END IN (${regiao_escolhida})
> OR
> '1 - Todos' IN (${regiao_escolhida})
> )
> AND
> (producao.irrigado IN (${sistema_de_cultivo}) OR '1 - Todos' IN (${sistema_de_cultivo}))
> AND (produto.nome IN (${escolha_produto}) OR '1 - Todos' IN (${escolha_produto}))
> GROUP BY REGIAO_NOME, grupo.nome_grupo, produto.nome
> ORDER BY REGIAO_NOME, grupo.nome_grupo, produto.nome;
>   at org.pentaho.reporting.engine.classic.core.modules.misc.datafactory.sql.SimpleSQLReportDataFactory.queryData(SimpleSQLReportDataFactory.java:183)
>   at org.pentaho.reporting.engine.classic.core.modules.misc.datafactory.sql.SQLReportDataFactory.queryData(SQLReportDataFactory.java:142)
>   at org.pentaho.reporting.engine.classic.core.CompoundDataFactory.queryStaticInternal(CompoundDataFactory.java:172)
>   at org.pentaho.reporting.engine.classic.core.CompoundDataFactory.queryStatic(CompoundDataFactory.java:154)
>   at org.pentaho.reporting.engine.classic.core.cache.CachingDataFactory.queryInternal(CachingDataFactory.java:408)
>   at org.pentaho.reporting.engine.classic.core.cache.CachingDataFactory.queryStatic(CachingDataFactory.java:151)
>   at org.pentaho.reporting.engine.classic.core.CompoundDataFactory.queryStaticInternal(CompoundDataFactory.java:168)
>   at org.pentaho.reporting.engine.classic.core.CompoundDataFactory.queryStatic(CompoundDataFactory.java:154)
>   at org.pentaho.reporting.engine.classic.core.CompoundDataFactory.queryData(CompoundDataFactory.java:67)
>   at org.pentaho.reporting.engine.classic.core.states.datarow.DefaultFlowController.performQueryData(DefaultFlowController.java:248)
>   at org.pentaho.reporting.engine.classic.core.states.datarow.DefaultFlowController.performQuery(DefaultFlowController.java:186)
>   at org.pentaho.reporting.engine.classic.core.states.process.ProcessState.initializeForMasterReport(ProcessState.java:317)
>   at org.pentaho.reporting.engine.classic.core.layout.output.AbstractReportProcessor.prepareReportProcessing(AbstractReportProcessor.java:425)
>   at org.pentaho.reporting.engine.classic.core.modules.output.pageable.graphics.PrintReportProcessor.getNumberOfPages(PrintReportProcessor.java:69)
>   at org.pentaho.reporting.engine.classic.core.modules.gui.base.PreviewPane$RepaginationRunnable.run(PreviewPane.java:238)
>   at org.pentaho.reporting.engine.classic.core.util.Worker.run(Worker.java:153)
> Caused by: org.postgresql.util.PSQLException: ERROR: function valida_valor(integer, integer, integer) does not exist
>   Hint: No function matches the given name and argument types. You might need to add explicit type casts.
>   Position: 246
>   at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
>   at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
>   at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
>   at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
>   at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
>   at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:304)
>   at org.pentaho.reporting.engine.classic.core.modules.misc.datafactory.sql.SimpleSQLReportDataFactory.parametrizeAndQuery(SimpleSQLReportDataFactory.java:311)
>   at org.pentaho.reporting.engine.classic.core.modules.misc.datafactory.sql.SimpleSQLReportDataFactory.queryData(SimpleSQLReportDataFactory.java:178)
>   ... 15 more

**Comment by DaniloSI** [comment]
Rodrigo, essa função está compilada no seu PC?

Tenta o arquivo "consulta.sql" no PG Admin 3, seleciona toda a função valida_valor e aperta F5.

**Comment by rdccosmo** [comment]
@DaniloSI não entendi, como disponibilizo a função valida_valor pro relatório no report designer?

**Comment by Sakamotto** [comment]
Basta executá-la no PGAdmin, em nossa base de dados, normalmente, como qualquer outra consulta. Isso deve funcionar kkk. Qualquer coisa fala aê :D

**Comment by DaniloSI** [comment]
Boa tarde, Rodrigo.

Acabamos de fazer um Push para o github com uma nova versão de todos os relatórios. Nessa nova versão, o parâmetro de cada relatório foi definido para que aparecesse na horizontal. Além disso, o SQL foi otimizado e, com essa otimização, a função valida_valor não é mais utilizada nem necessária. Assim, que a nova versão for disponibilizada no github, baixe-a e tente executar os novos relatórios, por favor.

**Comment by Sakamotto** [comment]
Boa tarde, Rodrigo. Você poderia testar agora com essa nova atualização? :D

**Comment by rdccosmo** [comment]
eu atualizo o issue assim que testar amanhã @sakamotto @danilosi

**Comment by Sakamotto** [comment]
Okay! xD

**Comment by rdccosmo** [comment]
tive alguns problemas com as ultimas atualizaçoes. vou fechar o issue e reabri-lo ou abrir outros se for o caso

**Comment by Sakamotto** [comment]
Blz. Esquecemos de dizer que você precisa executar o backup do banco novamente, pois alteramos algumas funções. xD
