### ISSUE TITLE
Problema nas conexões da transformação extrai_produto_subgrupo.ktr

### ISSUE THREAD

**Issue by rdccosmo** [LEDS/sipac#49]
No join "Merge Join 2" há algum problema com as conexões de entrada "InitCap" e "Sort rows 2". O Seguinte erro aparece:

> 2016/09/01 15:43:28 - Merge Join 2.0 - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : Exactly two input streams must be supplied
> 2016/09/01 15:43:28 - Merge Join 2.0 - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : Error initializing step [Merge Join 2]

**Comment by Sakamotto** [comment]
Acho que o problema é que no Merge Join, um dos comboBox que tem lá dentro não está preenchido. Isso é tranquilo. Você conseguiu executar o novo Backup? Pois nele contém as novas funções que precisam ser usadas para os relatórios. Aí não dá erro mais xD

**Comment by rdccosmo** [comment]
Para solucionar recriei as conexões e quando aparece no cursor especifico as entradas com "Left hand side stream of the join" e "Right hand side stream of the join" respectivamente

**Comment by paulossjunior** [comment]
pode fechar?

**Comment by rdccosmo** [comment]
preciso confirmar com 47e0a67
