### ISSUE TITLE
Error batch inserting rows into table [agricultura_producao]

### ISSUE THREAD

**Issue by rdccosmo** [LEDS/sipac#50]
Esse erro aparece ao executar a transformação extrai_produto.ktr

> 2016/09/01 15:49:07 - Tabela Produção.0 - ERROR: column "preco" of relation "agricultura_producao" does not exist
> 2016/09/01 15:49:07 - Tabela Produção.0 -   Position: 138
> 2016/09/01 15:49:07 - Tabela Produção.0 - 
> 2016/09/01 15:49:07 - Tabela Produção.0 - 
> 2016/09/01 15:49:07 - Tabela Produção.0 - Error updating batch
> 2016/09/01 15:49:07 - Tabela Produção.0 - Batch entry 0 INSERT INTO agricultura_producao (ano, mes, area_plantada, producao, area_colhida, area_em_formacao, irrigado, municipio_id, produto_id, preco) VALUES ( 2014,  4,  20,  50,  20,  NULL,  'S',  33,  157,  NULL) was aborted.  Call getNextException to see the cause.

**Comment by Sakamotto** [comment]
Essa transformação não deve ser executada. Quando você clica na pasta "Transformações" do repositório no github, você consegue ver, no README.md, a sequência de passos :D

1º: extrai_estado.ktr 
2º: extrai_meso.ktr 
3º: extrai_micro.ktr 
4º: extrai_municipio.ktr 
5º: extrai_grupos.ktr 
6º: extrai_produto_subgrupo.ktr 
7º: extrai_producao.ktr

**Comment by rdccosmo** [comment]
Desculpa, errei. É na transformação extrai producao.ktr msm que acontece esse erro.

Removi o table field preco da Tabela Produção na transformação pra poder funcionar.

**Comment by paulossjunior** [comment]
ainda está aberta essa issue?

**Comment by rdccosmo** [comment]
sim. vou testar na segunda feira com planilhas com preços
