### ISSUE TITLE
Unexpected conversion error while converting value [PRECO_MEDIO_ANUAL String] to a Number

### ISSUE THREAD

**Issue by rdccosmo** [LEDS/sipac#67]
Ao realizar a transformação [extrai_producao.ktr](https://github.com/LEDS/sipac/blob/a5fc0ba3f149f6ad533b60d9d611f97865a7b703/transformacoes/extrai_producao.ktr) após seguir a sequência em [transformacoes.sh](https://github.com/LEDS/sipac/blob/a5fc0ba3f149f6ad533b60d9d611f97865a7b703/transformacoes.sh#L3-L15) acontece o seguinte erro:
```
Tabela Produção.0 - PRECO_MEDIO_ANUAL String : couldn't convert String to number : non-numeric character found at position 3 for value [45,2]
```
Pode verificar isso, @irancaetano?

**Comment by irancaetano** [comment]
@rdccosmo foram identificados dois problemas já solucionados:
1 - erro de conexão com o banco de dados, devido a número da porta inválido: alterado de  32768 para 5432
2 - erro na conversão da planilha ODS para CSV. O conjunto de caracteres correto deve ser UTF-8

**Comment by rdccosmo** [comment]
OK @irancaetano não vou poder validar agora, mas vou fechar o issue.
Se tiver problemas reabro. Obrigado.
